### ISSUE TITLE
Spelling Mistake + Parameter Name Mistake

### ISSUE THREAD

**Issue by master30112001** [100mslive/100ms-docs#1159]
https://github.com/100mslive/100ms-docs/blob/main/docs/javascript/v2/features/chat.mdx

Problem 1: 
In React to get the broadcast messages, spelling mistake:
brodacast should be broadcast
(Search brodacast and you will get the error)

Problem 2:
Check the line above the "brodacast"
the parameter of selecting all messages - `selectMessages` should be `selectHMSMessages`

I wish to work on this and I am creating a PR soon.

**Comment by arjunattam** [comment]
thanks for the PR
