### ISSUE TITLE
copied popup in the bottom

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#242]
To reproduce:

Visit https://docs.100ms.live/javascript/v2/guides/react-quickstart

Click on Copy in one of the Code Snippets

<img width="134" alt="Screenshot 2021-10-02 at 8 11 41 AM" src="https://user-images.githubusercontent.com/61158210/135701305-322465cc-5356-4023-add5-a177d20cae43.png">

You can see that the "Copied" popup is at the bottom 

If you're planning to fix this just remove the popup and replace the copy icon with `Check` icon

Refer to this implementation [here](https://www.radix-ui.com/docs/primitives/components/alert-dialog#installation)

**Comment by somesh202** [comment]
Can I work on this issue?
