### ISSUE TITLE
syntax line highlighting not working 

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#243]
To reproduce: 

Visit: https://docs.100ms.live/javascript/v2/guides/react-quickstart#changing-ui-based-on-connection-state

Make the viewport small and scroll horizontally the code block as you can see the highlighting isn't covering the width

> NOTE: all styles are present in [`theme.css`](https://github.com/100mslive/100ms-docs/blob/main/styles/theme.css)

<img width="758" alt="Screenshot 2021-10-02 at 8 17 35 AM" src="https://user-images.githubusercontent.com/61158210/135701431-f1bc8419-2fae-4270-8a06-32523299a03d.png">

**Comment by olemon403** [comment]
i'm up to do it
