### ISSUE TITLE
home page for docs 

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#245]
Currently, there's no home for docs visiting https://docs.100ms.live/ would redirect to javascript docs

We should have a page that will have

- starter guide
- links to faq etc

Examples

- [Railway's docs](https://docs.railway.app/)
- [Vercel's docs](https://vercel.com/docs/concepts)
- [Supabase's docs](https://supabase.io/docs)

**Comment by bmbshlly** [comment]
Hey @Deep-Codes it's done!  check it out -> https://www.100ms.live/docs
