### ISSUE TITLE
improve note component

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#246]
Currently, Blockquotes are mapped a Custom Note component 

refer this :

https://github.com/100mslive/100ms-docs/blob/1f0d794c0111490b5e84b6fb08563253e0837621/components/MDXComponents.tsx#L19

https://github.com/100mslive/100ms-docs/blob/1f0d794c0111490b5e84b6fb08563253e0837621/components/MDXComponents.tsx#L58

Our current Note component looks like this:

Visit https://docs.100ms.live/javascript/v2/features/device-change check it live.

<img width="822" alt="Screenshot 2021-10-02 at 8 23 29 AM" src="https://user-images.githubusercontent.com/61158210/135701560-99540cf0-7223-4b3f-bd0b-56aed008abd6.png">

It looks very simple at the moment

Things that can make it better

- add an info icon 
- have a background , border (shades of blue / yellow / red)
- more variants ( success , note , error )

Feel free to drop questions if you have

**Comment by Deep-Codes** [comment]
Things to add:

Note component would have 3 variants (contrast type):

- warning
- success (default)
- error

every variant will have 3 colors having the following

- border =>  lighter of (red , blue , yellow)
- background => transparent lightest of (red , blue , yellow)
- left-border =>  light of (red , blue , yellow)

Choose colors from [Radiux](https://www.radix-ui.com/colors)
Get to know more about choosing the following variants from [here](https://www.radix-ui.com/docs/colors/palette-composition/understanding-the-scale)

Feel free to ask me

**Comment by mohit-cfc** [comment]
Will try working ont this one

**Comment by somesh202** [comment]
Can I work on this issue? @Deep-Codes

**Comment by Deep-Codes** [comment]
> Can I work on this issue? @Deep-Codes

Sure go for it. let me know if help needed.
