### ISSUE TITLE
automatically update table of content navigation based on scroll position

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#247]
based on the scroll the specific table of content is highlighted

![toc](https://user-images.githubusercontent.com/61158210/135702302-79368a9c-b71c-49b2-abcb-7407ac7e7055.gif)

Table of Content is implemented [here](https://github.com/100mslive/100ms-docs/blob/main/components/Toc.tsx).

**Comment by Apoorve73** [comment]
I would like to take this up. Thanks!

**Comment by Deep-Codes** [comment]
> I would like to take this up. Thanks!

Awesome , Let me know if help needed

**Comment by ranjithkumark8** [comment]
Hi @Deep-Codes R u working on this issue?

**Comment by Deep-Codes** [comment]
> Hi @Deep-Codes R u working on this issue?

Nope @Apoorve73 is working on it.
If you want to contribute you can check all our open issues [here](https://github.com/100mslive/100ms-docs/issues)

**Comment by Deep-Codes** [comment]
@Apoorve73 any update?
Let me know if you need any help

**Comment by OatLatte** [comment]
OMG Thank you! I love this component!

**Comment by Nixon-Samuel** [comment]
This is added now.
