### ISSUE TITLE
Indicator flag(active) is still true after disabling room using API

### ISSUE THREAD

**Issue by satiye** [100mslive/100ms-docs#439]
After calling API  to disable a room, response comes with success 200, but active field comes still as true.

**Comment by satiye** [comment]
But, in the response body, I don't get any indicator about 'room ending'. Only it has active field which is true and any other properties.

In the documentation, active is referenced as a flag to indicate disabling of the room : https://www.100ms.live/docs/server-side/v2/features/room#disable-room

**Comment by Nixon-Samuel** [comment]
@satiye You can check the `enabled` field in the response to validate whether the room is disabled or not. Refer to the [doc](https://www.100ms.live/docs/server-side/v2/Rooms/disable-or-enable) for more info.
