### ISSUE TITLE
Text selection is not visible in dark mode

### ISSUE THREAD

**Issue by pawan-100ms** [100mslive/100ms-docs#526]
Switch to dark mode and try to copy some text. It's really annoying that selection is not visible.

**Comment by Deep-Codes** [comment]
> Switch to dark mode and try to copy some text. It's really annoying that selection is not visible.

Visibile for me tho

<img width="788" alt="Screenshot 2022-04-21 at 7 14 41 PM" src="https://user-images.githubusercontent.com/61158210/164471425-2087cbe0-d5cb-47d1-b172-65c0f52a32f1.png">

@pawan-100ms Give some more context

**Comment by pawan-100ms** [comment]
I am using Safari on Mac
<img width="756" alt="Screenshot 2022-04-21 at 7 23 34 PM" src="https://user-images.githubusercontent.com/103245157/164473900-9ddb8275-1afa-49b7-b731-2b547f431917.png">
.

**Comment by pawan-100ms** [comment]
Just checked it's visible on chrome but not Safari.

**Comment by pawan-100ms** [comment]
@Deep-Codes did you find any fix for this?

**Comment by Deep-Codes** [comment]
> @Deep-Codes did you find any fix for this?

Hey Currently giving exams so didn't have time to look into it. but anyways opened a PR for the fix 👍🏽.

**Comment by arjunattam** [comment]
Closing this since the PR is merged
