### ISSUE TITLE
markdown parsing should be able to handle consecutive lines with headings

### ISSUE THREAD

**Issue by arjunattam** [100mslive/100ms-docs#930]
and avoid the need for this additional `<br/>`

<img width="375" alt="Screenshot 2022-12-05 at 4 10 38 PM" src="https://user-images.githubusercontent.com/284612/205773909-e0641405-ea33-4bb4-807b-39964e99ff96.png">

**Comment by KaustubhKumar05** [comment]
Resolved here: https://github.com/100mslive/100ms-docs/pull/1012
